import create from 'zustand'

const useStore = create((set) => ({
 minArea: 20,
 maxArea: 100,
 minPrice: 7,
 maxPrice: 15,
 min: 30,
 max: 50,
 min2: 8,
 max2: 11,
 floor_min: 1,
 floor_max: 13,
 floorFrom:1,
 floorTo:8,
 valueOption: "Жилые",
 valueOption2: "Комфорт",
 type:1,
 clas:1,
 video_home:"",
 video_complex:"",
 video_home_img:"",
 video_complex_img:"",

 setmin: (min) => set({ min }),
 setmax: (max) => set({ max }),
 setmin2: (min2) => set({ min2 }),
 setmax2: (max2) => set({ max2 }),
 setvalueOption: (valueOption) => set({ valueOption }),
 setvalueOption2: (valueOption2) => set({ valueOption2 }),
 setType: (type) => set({ type }),
 setClass: (clas) => set({ clas }),
 setMinArea: (minArea) => set({ minArea }),
 setMaxArea: (maxArea) => set({ maxArea }),
 setMinPrice: (minPrice) => set({ minPrice }),
 setMaxPrice: (maxPrice) => set({ maxPrice }),
 setMinFloor: (floor_min) => set({ floor_min }),
 setMaxFloor: (floor_max) => set({ floor_max }),
 setVideoHome: (video_home) => set({ video_home }),
 setVideoComplex: (video_complex) => set({ video_complex }),
 setVideoHomeImg: (video_home_img) => set({ video_home_img }),
 setVideoComplexImg: (video_complex_img) => set({ video_complex_img }),
 setFloorFrom: (floorFrom) => set({ floorFrom }),
 setFloorTo: (floorTo) => set({ floorTo }),
}))

export default useStore